owner: tacxtv
repo: fr.tacxtv.status

sites:
  - name: gateway.tacxtv.fr
    url: gateway.tacxtv.fr
    check: "tcp-ping"
    port: 53

  - name: tacxtv.fr
    url: https://tacxtv.fr

  - name: eco.tacxtv.fr
    url: https://eco.tacxtv.fr/

  # - name: eco.tacxtv.fr (game)
  #   url: eco.tacxtv.fr
  #   check: "tcp-ping"
  #   port: 3001

  - name: miratopia.tacxtv.fr
    url: https://miratopia.tacxtv.fr

workflowSchedule:
  uptime: "*/15 * * * *"

assignees: # Users to assign downtime issues (optional)
  - tacxou

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.tacxtv.fr
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status/TacxTV
  introTitle: Status/TacxTV
  introMessage: uptime
  navbar:
    - title: Status
      href: /
#     - title: GitHub
#       href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
