owner: tacxtv
repo: fr.tacxtv.status

sites:
  - name: Google
    url: https://google.fr/
  - name: Libertech
    url: http://libertech.fr

workflowSchedule:
  uptime: "*/15 * * * *"

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.tacxtv.fr
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status/TacxTV
  introTitle: Status/TacxTV
  introMessage: uptime
  navbar:
    - title: Status
      href: /
#     - title: GitHub
#       href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
